name: Build AWS AMI with Packer

on:
  push:
    branches:
      - main # sau branch-ul tău principal

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Run `packer init`
        run: packer init ./packer

      - name: Run `packer build`
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build ./packer/wordpress-aws-ubuntu.pkr.hcl
        working-directory: ./packer
